# Generated by Django 4.2 on 2025-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0004_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='extra_permissions',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identity_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='身份ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_identity_bound',
            field=models.BooleanField(default=False, verbose_name='是否已绑定'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('maintenance', '维修人员'), ('dorm_manager', '宿管'), ('admin', '超级管理员')], default='student', max_length=20, verbose_name='身份角色'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('设备故障', '设备故障'), ('水电问题', '水电问题'), ('网络连接', '网络连接'), ('柜子损坏', '柜子损坏'), ('门窗损坏', '门窗损坏'), ('其他', '其他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', '待派单'), ('repairing', '维修中'), ('finished', '维修完成(待评价)'), ('closed', '已结单'), ('rejected', '已驳回')], default='pending_dispatch', max_length=20),
        ),
        migrations.DeleteModel(
            name='OARequest',
        ),
    ]
