# Generated by Django 4.2 on 2025-12-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0005_remove_customuser_extra_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='故障描述'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', '正在处理'), ('repairing', '维修中'), ('finished', '维修完成(待评价)'), ('closed', '已结单'), ('rejected', '已驳回')], default='pending_dispatch', max_length=20),
        ),
    ]
